### ISSUE TITLE
Things go wrong when navigating "Back to THINQ.tv"

### ISSUE THREAD

**Issue by taangle** [taangle/thinqtv-android#17]
When a page is broken (like right now, "Invite Us to Speak" -> "Your Online Mom") and then the user clicks the "Back to THINQ.tv" button, things go wrong.

_Originally posted by @taangle in https://github.com/taangle/thinqtv-android/pull/16#issuecomment-601868361_

**Comment by anibalb2500** [comment]
With my pull request to dev, this issue should be resolved.
