### ISSUE TITLE
The boxes on the Bystander Guidelines page are messed up.

### ISSUE THREAD

**Issue by taangle** [taangle/thinqtv-android#18]
The boxes don't really work, the descriptions additional info doesn't pop up when you tap them. Also, scrolling is totally messed up when you try to open one of the boxes.

_Originally posted by @taangle in https://github.com/taangle/thinqtv-android/pull/16#issuecomment-602142876_

**Comment by anibalb2500** [comment]
Currently removed the Bystander Guidelines option from the drop down menu in the get involved pages. The bystander guidelines was too mobile unfriendly for the way I've typically been using Webviews, so I'll have to get more with Javascript before I'm able to resolve this issue, so I will come back to this
